### ISSUE TITLE
Notify when club state is ending

### ISSUE THREAD

**Issue by lukynmatuska** [su-fit-vut/kachna-online#119]
Please add notification about end of chillzone for example.

Because LeO don't like when calendar look like this:
![Screenshot_20220504_115714](https://user-images.githubusercontent.com/19732513/166660773-bda047a1-60bf-4d10-9d16-2c3a765cd5c4.png)

*KachnaBot webhook* should send message with tag of chillmaster to #chillzone-log channel for example.

So chillmaster can extend the current chillzone (or other club state).

**Comment by ondryaso** [comment]
This would require reworking the `StatePlannerBackgroundService` and its callers to wake up earlier than at the end of a state, trigger the 'pre-end' actions and then sleep until the end of the state. I don't think this would be _too much work_ but it would require thourough testing of the state lifetime thing which is non-trivial. 

However, I don't really think this is necessary. To make the calendar less cluttered, I think it would be better to just merge successive events of the same type (that could be done either on backend or on frontend; I'm not entirely sure which of these two options would be better).

Most importantly: People that open a chillzone should be aware of what they're doing. They've got responsibility for the club; if you aren't able to remember what time you opened for, I'm not sure if you're capable of watching over the club and all the people in it. 😄 I'm sure you wouldn't mind but in my opinion, this would only create more useless clutter in the #chillzone-log channel.
