### ISSUE TITLE
Show state date in event details

### ISSUE THREAD

**Issue by ondryaso** [su-fit-vut/kachna-online#125]
When an event spans over multiple days and club states are linked to it, it's not clear which day the state occurs on.

![Screenshot 2022-09-02 134248](https://user-images.githubusercontent.com/1338916/188132476-ef9bd03b-311c-4ce3-9974-01baf108b588.jpg)

**Comment by FrNecas** [comment]
Fixed in #124

**Comment by ondryaso** [comment]
Fixed in #124.
