### ISSUE TITLE
Ignoring whitespace at the beginning of a new line

### ISSUE THREAD

**Issue by huhuwashere** [su-fit-vut/kachna-online#126]
No whitespaces at the beginning of a new line when needed in the description of an event. When you intentionally write white spaces at the beginning of a new line as an indentation you will see it only in edit mode.

Event preview
![image](https://user-images.githubusercontent.com/74883063/193333993-502f5018-5977-46c2-b003-801626f6e948.png)

Edit mode
![image](https://user-images.githubusercontent.com/74883063/193334093-676b9e63-4f65-4b3a-b538-c9c552ac55b7.png)

**Comment by ondryaso** [comment]
This is basically a part of #115, I added a comment there not to forget about this and I'm closing this issue.
