### ISSUE TITLE
Event detail opened from expanded day view does not close by clicking on a different detail.

### ISSUE THREAD

**Issue by Zeftax** [su-fit-vut/kachna-online#139]
# Steps to replicate

1. Zoom out of the kachna online page enough, so that the "+x další" button appers on some days.  
![image](https://github.com/su-fit-vut/kachna-online/assets/46405012/75448892-02fe-48ad-b0d4-2642c4448c89)  
2.  Expand the day by clicking on the "+x další" button.  
3. Open the detail of an event.  
4. Open the detail of an event from the same day again.  

# Expected behaviour

The old event preview should disappear upon clinking anywhere but on the event detail modal.  

# Actual behaviour

The new events detail will open over the old one, this can be repeated ad libitum, as show in the picture below.  

![image](https://github.com/su-fit-vut/kachna-online/assets/46405012/b3922ed5-abb8-4d1e-85bd-f954686f1455)

**Comment by azooz59T** [comment]
Can I take this and can I confirm my understanding you want the old event preview to disappear when the a new one is clicked ?

**Comment by Kiznoh** [comment]
Sure, feel free to take this.

The main problem is that the expanded day is on top of the backgroud of the modal with event/state detail.
That means you can open multiple modals instead of closing the open one and just then opening another one.
